"""add audio_file gender age_range to assets

Revision ID: 405fc7dead3c
Revises: a3f1c9b27e54
Create Date: 2026-05-27 13:31:47.176591

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '405fc7dead3c'
down_revision: str | Sequence[str] | None = 'a3f1c9b27e54'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_file', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('age_range', sa.String(length=32), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('age_range')
        batch_op.drop_column('gender')
        batch_op.drop_column('audio_file')

    # ### end Alembic commands ###
